[[main]]
  name = 'Artigos'
  identifier = 'articles'
  pageRef = '/articles'
  weight = 1

[[main]]
  name = 'Categorias'
  identifier = 'categories'
  pageRef = '/categories'
  weight = 2

[[main]]
  name = 'Séries'
  identifier = 'series'
  pageRef = '/series'
  weight = 3

[[more]]
  name = 'Sobre'
  identifier = 'about'
  pageRef = '/about'
  weight = 1

[[more]]
  name = 'Autores'
  identifier = 'authors'
  pageRef = '/authors'
  weight = 2

[[more]]
  name = 'Tags'
  identifier = 'tags'
  pageRef = '/tags'
  weight = 3

[[footer]]
  name = 'E-mail'
  identifier = 'email'
  url = 'mailto:contestthemindfield@gmail.com'
  pre = 'email'
  weight = 1

[[footer]]
  name = 'RSS'
  identifier = 'rss'
  url = '/pt-br/index.xml'
  pre = 'rss'
  weight = 2
